apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  nginx.conf: |
    events { }

    http {
        server {
            listen 80;

            server_name _;

            location / {
                return 200;
            }

            location /grafana/ {
                rewrite ^/grafana/(.*) /$1 break;
                proxy_pass http://kube-prometheus-stack-grafana;
                proxy_set_header Host $host;
            }
            location /dashboard/ {
                rewrite ^/dashboard/(.*) /$1 break;
                proxy_pass http://kubernetes-dashboard-web:8000;
                proxy_set_header Host $host;
            }
        }
    }